### ISSUE TITLE
Sounds are cutting off in the last 0.5 seconds when another is queued

### ISSUE THREAD

**Issue by jmpodhradsky** [paynejacob/speakerbob#42]
I've noticed that sounds are cutting off in the last milliseconds after they are played, particularly when there's another sound queued up afterwards

**To Reproduce**
1. Go to speakerbob
2. search for 'red alert' and play it
3. search for 'tim allen' and play/queue it while 'red alert' is playing
4. note how 'red alert' is cut off at the end.

**Comment by paynejacob** [comment]
This is probably due to the variable network latency getting the audio and the ws message coming in.  The FE should implement a queue and block until playback of the current sound completes.
